//! ASE データ型ドキュメントデータ

use super::{DocCategory, DocEntry};

/// ASE データ型エントリ
pub static DATATYPE_ENTRIES: &[DocEntry] = &[
    DocEntry {
        name: "INT",
        description: "Integer (-2^31 to 2^31-1, 4 bytes)",
        syntax: "INT",
        params: &[],
        category: DocCategory::DataType,
    },
    DocEntry {
        name: "INTEGER",
        description: "Integer (same as INT)",
        syntax: "INTEGER",
        params: &[],
        category: DocCategory::DataType,
    },
    DocEntry {
        name: "SMALLINT",
        description: "Small integer (-32768 to 32767, 2 bytes)",
        syntax: "SMALLINT",
        params: &[],
        category: DocCategory::DataType,
    },
    DocEntry {
        name: "TINYINT",
        description: "Tiny integer (0 to 255, 1 byte)",
        syntax: "TINYINT",
        params: &[],
        category: DocCategory::DataType,
    },
    DocEntry {
        name: "BIGINT",
        description: "Big integer (-2^63 to 2^63-1, 8 bytes)",
        syntax: "BIGINT",
        params: &[],
        category: DocCategory::DataType,
    },
    DocEntry {
        name: "REAL",
        description: "Floating point (4 bytes)",
        syntax: "REAL",
        params: &[],
        category: DocCategory::DataType,
    },
    DocEntry {
        name: "FLOAT",
        description: "Floating point (8 bytes)",
        syntax: "FLOAT[(n)]",
        params: &[],
        category: DocCategory::DataType,
    },
    DocEntry {
        name: "DOUBLE",
        description: "Double precision floating point (8 bytes)",
        syntax: "DOUBLE",
        params: &[],
        category: DocCategory::DataType,
    },
    DocEntry {
        name: "DECIMAL",
        description: "Exact numeric with precision and scale",
        syntax: "DECIMAL(p[, s])",
        params: &[],
        category: DocCategory::DataType,
    },
    DocEntry {
        name: "NUMERIC",
        description: "Exact numeric (same as DECIMAL)",
        syntax: "NUMERIC(p[, s])",
        params: &[],
        category: DocCategory::DataType,
    },
    DocEntry {
        name: "MONEY",
        description: "Monetary value (-922 trillion to 922 trillion, 8 bytes)",
        syntax: "MONEY",
        params: &[],
        category: DocCategory::DataType,
    },
    DocEntry {
        name: "SMALLMONEY",
        description: "Small monetary (-214748 to 214748, 4 bytes)",
        syntax: "SMALLMONEY",
        params: &[],
        category: DocCategory::DataType,
    },
    DocEntry {
        name: "CHAR",
        description: "Fixed-length character (up to 16384 chars)",
        syntax: "CHAR(n)",
        params: &[],
        category: DocCategory::DataType,
    },
    DocEntry {
        name: "VARCHAR",
        description: "Variable-length character (up to 16384 chars)",
        syntax: "VARCHAR(n)",
        params: &[],
        category: DocCategory::DataType,
    },
    DocEntry {
        name: "TEXT",
        description: "Variable-length text (up to 2GB)",
        syntax: "TEXT",
        params: &[],
        category: DocCategory::DataType,
    },
    DocEntry {
        name: "NCHAR",
        description: "Fixed-length Unicode (UTF-16)",
        syntax: "NCHAR(n)",
        params: &[],
        category: DocCategory::DataType,
    },
    DocEntry {
        name: "NVARCHAR",
        description: "Variable-length Unicode (UTF-16)",
        syntax: "NVARCHAR(n)",
        params: &[],
        category: DocCategory::DataType,
    },
    DocEntry {
        name: "UNICHAR",
        description: "Fixed-length Unicode (ASE specific, UTF-16)",
        syntax: "UNICHAR(n)",
        params: &[],
        category: DocCategory::DataType,
    },
    DocEntry {
        name: "UNIVARCHAR",
        description: "Variable-length Unicode (ASE specific, UTF-16)",
        syntax: "UNIVARCHAR(n)",
        params: &[],
        category: DocCategory::DataType,
    },
    DocEntry {
        name: "UNITEXT",
        description: "Variable-length Unicode text (ASE specific)",
        syntax: "UNITEXT",
        params: &[],
        category: DocCategory::DataType,
    },
    DocEntry {
        name: "BINARY",
        description: "Fixed-length binary data",
        syntax: "BINARY(n)",
        params: &[],
        category: DocCategory::DataType,
    },
    DocEntry {
        name: "VARBINARY",
        description: "Variable-length binary data",
        syntax: "VARBINARY(n)",
        params: &[],
        category: DocCategory::DataType,
    },
    DocEntry {
        name: "IMAGE",
        description: "Variable-length binary (up to 2GB)",
        syntax: "IMAGE",
        params: &[],
        category: DocCategory::DataType,
    },
    DocEntry {
        name: "DATE",
        description: "Date value (0001-01-01 to 9999-12-31)",
        syntax: "DATE",
        params: &[],
        category: DocCategory::DataType,
    },
    DocEntry {
        name: "TIME",
        description: "Time value (00:00:00 to 23:59:59)",
        syntax: "TIME",
        params: &[],
        category: DocCategory::DataType,
    },
    DocEntry {
        name: "DATETIME",
        description: "Date and time (1753-01-01 to 9999-12-31, 8 bytes)",
        syntax: "DATETIME",
        params: &[],
        category: DocCategory::DataType,
    },
    DocEntry {
        name: "SMALLDATETIME",
        description: "Small date and time (1900-01-01 to 2079-06-06, 4 bytes)",
        syntax: "SMALLDATETIME",
        params: &[],
        category: DocCategory::DataType,
    },
    DocEntry {
        name: "BIGDATETIME",
        description: "High-precision datetime (ASE 15.7+, 1/1000 sec)",
        syntax: "BIGDATETIME",
        params: &[],
        category: DocCategory::DataType,
    },
    DocEntry {
        name: "BIGTIME",
        description: "High-precision time (ASE 15.7+)",
        syntax: "BIGTIME",
        params: &[],
        category: DocCategory::DataType,
    },
    DocEntry {
        name: "TIMESTAMP",
        description: "Auto-updated binary (unique within database)",
        syntax: "TIMESTAMP",
        params: &[],
        category: DocCategory::DataType,
    },
    DocEntry {
        name: "BIT",
        description: "Boolean (0 or 1)",
        syntax: "BIT",
        params: &[],
        category: DocCategory::DataType,
    },
    DocEntry {
        name: "UNIQUEIDENTIFIER",
        description: "GUID/UUID (16 bytes)",
        syntax: "UNIQUEIDENTIFIER",
        params: &[],
        category: DocCategory::DataType,
    },
];
