//! ASE 組み込み関数ドキュメントデータ

use super::{DocCategory, DocEntry};

/// ASE 組み込み関数エントリ
pub static FUNCTION_ENTRIES: &[DocEntry] = &[
    // String functions
    DocEntry {
        name: "SUBSTRING",
        description: "Extracts a substring from a string expression",
        syntax: "SUBSTRING(expression, start, length)",
        params: &["expression", "start", "length"],
        category: DocCategory::Function,
    },
    DocEntry {
        name: "CHAR_LENGTH",
        description: "Returns the length of a string in characters",
        syntax: "CHAR_LENGTH(expression)",
        params: &["expression"],
        category: DocCategory::Function,
    },
    DocEntry {
        name: "LEN",
        description: "String length (trailing spaces not counted)",
        syntax: "LEN(expression)",
        params: &["expression"],
        category: DocCategory::Function,
    },
    DocEntry {
        name: "UPPER",
        description: "Converts a string to uppercase",
        syntax: "UPPER(expression)",
        params: &["expression"],
        category: DocCategory::Function,
    },
    DocEntry {
        name: "LOWER",
        description: "Converts a string to lowercase",
        syntax: "LOWER(expression)",
        params: &["expression"],
        category: DocCategory::Function,
    },
    DocEntry {
        name: "LTRIM",
        description: "Removes leading spaces",
        syntax: "LTRIM(expression)",
        params: &["expression"],
        category: DocCategory::Function,
    },
    DocEntry {
        name: "RTRIM",
        description: "Removes trailing spaces",
        syntax: "RTRIM(expression)",
        params: &["expression"],
        category: DocCategory::Function,
    },
    DocEntry {
        name: "STR_REPLACE",
        description: "Replaces all occurrences of a pattern in a string",
        syntax: "STR_REPLACE(source, pattern, replacement)",
        params: &["source", "pattern", "replacement"],
        category: DocCategory::Function,
    },
    DocEntry {
        name: "STUFF",
        description: "Deletes and inserts characters at a specified position",
        syntax: "STUFF(source, start, length, insert)",
        params: &["source", "start", "length", "insert"],
        category: DocCategory::Function,
    },
    DocEntry {
        name: "REPLICATE",
        description: "Repeat string N times",
        syntax: "REPLICATE(expression, n)",
        params: &["expression", "n"],
        category: DocCategory::Function,
    },
    DocEntry {
        name: "SPACE",
        description: "Generate N spaces",
        syntax: "SPACE(n)",
        params: &["n"],
        category: DocCategory::Function,
    },
    DocEntry {
        name: "REVERSE",
        description: "Reverse string",
        syntax: "REVERSE(expression)",
        params: &["expression"],
        category: DocCategory::Function,
    },
    DocEntry {
        name: "LEFT",
        description: "Returns the left part of a string with the specified number of characters",
        syntax: "LEFT(expression, n)",
        params: &["expression", "n"],
        category: DocCategory::Function,
    },
    DocEntry {
        name: "RIGHT",
        description: "Returns the right part of a string with the specified number of characters",
        syntax: "RIGHT(expression, n)",
        params: &["expression", "n"],
        category: DocCategory::Function,
    },
    DocEntry {
        name: "CHARINDEX",
        description: "Find pattern position (1-based)",
        syntax: "CHARINDEX(pattern, expression)",
        params: &["pattern", "expression"],
        category: DocCategory::Function,
    },
    DocEntry {
        name: "PATINDEX",
        description: "Pattern index using wildcards (1-based)",
        syntax: "PATINDEX('%pattern%', expression)",
        params: &["pattern", "expression"],
        category: DocCategory::Function,
    },
    // Numeric functions
    DocEntry {
        name: "ABS",
        description: "Absolute value",
        syntax: "ABS(expression)",
        params: &["expression"],
        category: DocCategory::Function,
    },
    DocEntry {
        name: "CEILING",
        description: "Smallest integer >= value",
        syntax: "CEILING(expression)",
        params: &["expression"],
        category: DocCategory::Function,
    },
    DocEntry {
        name: "FLOOR",
        description: "Largest integer <= value",
        syntax: "FLOOR(expression)",
        params: &["expression"],
        category: DocCategory::Function,
    },
    DocEntry {
        name: "ROUND",
        description: "Rounds a numeric value to n decimal places",
        syntax: "ROUND(expression, n)",
        params: &["expression", "n"],
        category: DocCategory::Function,
    },
    DocEntry {
        name: "SQRT",
        description: "Square root",
        syntax: "SQRT(expression)",
        params: &["expression"],
        category: DocCategory::Function,
    },
    DocEntry {
        name: "POWER",
        description: "Raise to power",
        syntax: "POWER(expression, n)",
        params: &["expression", "n"],
        category: DocCategory::Function,
    },
    DocEntry {
        name: "SIGN",
        description: "Sign of value (-1, 0, 1)",
        syntax: "SIGN(expression)",
        params: &["expression"],
        category: DocCategory::Function,
    },
    // Date functions
    DocEntry {
        name: "GETDATE",
        description: "Current date and time",
        syntax: "GETDATE()",
        params: &[],
        category: DocCategory::Function,
    },
    DocEntry {
        name: "DATEADD",
        description: "Adds an interval to a date",
        syntax: "DATEADD(unit, number, date)",
        params: &["unit", "number", "date"],
        category: DocCategory::Function,
    },
    DocEntry {
        name: "DATEDIFF",
        description: "Returns the difference between two dates",
        syntax: "DATEDIFF(unit, date1, date2)",
        params: &["unit", "date1", "date2"],
        category: DocCategory::Function,
    },
    DocEntry {
        name: "DATEPART",
        description: "Extracts a part of a date as an integer",
        syntax: "DATEPART(unit, date)",
        params: &["unit", "date"],
        category: DocCategory::Function,
    },
    DocEntry {
        name: "DATENAME",
        description: "Extract date part as string",
        syntax: "DATENAME(unit, date)",
        params: &["unit", "date"],
        category: DocCategory::Function,
    },
    DocEntry {
        name: "DAY",
        description: "Day of month (1-31)",
        syntax: "DAY(date)",
        params: &["date"],
        category: DocCategory::Function,
    },
    DocEntry {
        name: "MONTH",
        description: "Month number (1-12)",
        syntax: "MONTH(date)",
        params: &["date"],
        category: DocCategory::Function,
    },
    DocEntry {
        name: "YEAR",
        description: "Year number",
        syntax: "YEAR(date)",
        params: &["date"],
        category: DocCategory::Function,
    },
    // Conversion functions
    DocEntry {
        name: "CONVERT",
        description: "Converts an expression to the specified data type",
        syntax: "CONVERT(type, expression[, style])",
        params: &["type", "expression", "style"],
        category: DocCategory::Function,
    },
    DocEntry {
        name: "CAST",
        description: "Converts an expression to the specified data type",
        syntax: "CAST(expression AS type)",
        params: &["expression", "type"],
        category: DocCategory::Function,
    },
    // Aggregate functions
    DocEntry {
        name: "COUNT",
        description: "Returns the number of rows",
        syntax: "COUNT([DISTINCT] expression | *)",
        params: &["expression"],
        category: DocCategory::Function,
    },
    DocEntry {
        name: "SUM",
        description: "Returns the sum of values",
        syntax: "SUM([DISTINCT] expression)",
        params: &["expression"],
        category: DocCategory::Function,
    },
    DocEntry {
        name: "AVG",
        description: "Returns the average of values",
        syntax: "AVG([DISTINCT] expression)",
        params: &["expression"],
        category: DocCategory::Function,
    },
    DocEntry {
        name: "MIN",
        description: "Returns the minimum value",
        syntax: "MIN(expression)",
        params: &["expression"],
        category: DocCategory::Function,
    },
    DocEntry {
        name: "MAX",
        description: "Returns the maximum value",
        syntax: "MAX(expression)",
        params: &["expression"],
        category: DocCategory::Function,
    },
    // System functions
    DocEntry {
        name: "ISNULL",
        description: "Replaces NULL with the specified replacement value",
        syntax: "ISNULL(expression, replacement)",
        params: &["expression", "replacement"],
        category: DocCategory::Function,
    },
    DocEntry {
        name: "COALESCE",
        description: "Returns the first non-NULL expression",
        syntax: "COALESCE(expr1, expr2, ...)",
        params: &["expr1", "expr2", "..."],
        category: DocCategory::Function,
    },
    DocEntry {
        name: "NULLIF",
        description: "NULL if expressions are equal",
        syntax: "NULLIF(expr1, expr2)",
        params: &["expr1", "expr2"],
        category: DocCategory::Function,
    },
    DocEntry {
        name: "IDENTITY",
        description: "Identity column value",
        syntax: "IDENTITY",
        params: &[],
        category: DocCategory::Function,
    },
    DocEntry {
        name: "OBJECT_ID",
        description: "Database object ID",
        syntax: "OBJECT_ID('object_name')",
        params: &["object_name"],
        category: DocCategory::Function,
    },
    DocEntry {
        name: "COL_LENGTH",
        description: "Column length in bytes",
        syntax: "COL_LENGTH('table', 'column')",
        params: &["table", "column"],
        category: DocCategory::Function,
    },
    DocEntry {
        name: "VALID_NAME",
        description: "Check if identifier is valid",
        syntax: "VALID_NAME('name')",
        params: &["name"],
        category: DocCategory::Function,
    },
];

// ---------------------------------------------------------------------------
// System variable entries
// ---------------------------------------------------------------------------
