//! ASE SQLキーワードドキュメントデータ

use super::{DocCategory, DocEntry};

/// ASE SQLキーワードエントリ
pub static KEYWORD_ENTRIES: &[DocEntry] = &[
    DocEntry {
        name: "SELECT",
        description: "Retrieves data from one or more tables",
        syntax: "SELECT [DISTINCT] col1, col2 FROM table WHERE condition",
        params: &[],
        category: DocCategory::Keyword,
    },
    DocEntry {
        name: "FROM",
        description: "Specifies the source tables for a query",
        syntax: "FROM table1 [AS alias] [JOIN table2 ON ...]",
        params: &[],
        category: DocCategory::Keyword,
    },
    DocEntry {
        name: "WHERE",
        description: "Filters rows based on a condition",
        syntax: "WHERE column = value AND column2 > value2",
        params: &[],
        category: DocCategory::Keyword,
    },
    DocEntry {
        name: "INSERT",
        description: "Inserts rows into a table",
        syntax: "INSERT INTO table (col1, col2) VALUES (val1, val2)",
        params: &[],
        category: DocCategory::Keyword,
    },
    DocEntry {
        name: "INTO",
        description: "Target specification for INSERT/SELECT INTO",
        syntax: "INSERT INTO table ...",
        params: &[],
        category: DocCategory::Keyword,
    },
    DocEntry {
        name: "UPDATE",
        description: "Modifies existing rows in a table",
        syntax: "UPDATE table SET col1 = val1 WHERE condition",
        params: &[],
        category: DocCategory::Keyword,
    },
    DocEntry {
        name: "DELETE",
        description: "Removes rows from a table",
        syntax: "DELETE FROM table WHERE condition",
        params: &[],
        category: DocCategory::Keyword,
    },
    DocEntry {
        name: "CREATE",
        description: "Creates a new database object",
        syntax: "CREATE TABLE | PROCEDURE | VIEW | INDEX ...",
        params: &[],
        category: DocCategory::Keyword,
    },
    DocEntry {
        name: "ALTER",
        description: "Modifies an existing database object",
        syntax: "ALTER TABLE ... | ALTER PROCEDURE ...",
        params: &[],
        category: DocCategory::Keyword,
    },
    DocEntry {
        name: "DROP",
        description: "Removes a database object",
        syntax: "DROP TABLE | PROCEDURE | VIEW | INDEX ...",
        params: &[],
        category: DocCategory::Keyword,
    },
    DocEntry {
        name: "TABLE",
        description: "Defines or references a table structure",
        syntax: "CREATE TABLE name (col1 TYPE, ...)",
        params: &[],
        category: DocCategory::Keyword,
    },
    DocEntry {
        name: "INDEX",
        description: "Creates an index on table columns",
        syntax: "CREATE [UNIQUE] [CLUSTERED] INDEX name ON table(col)",
        params: &[],
        category: DocCategory::Keyword,
    },
    DocEntry {
        name: "VIEW",
        description: "Creates a virtual table based on a query",
        syntax: "CREATE VIEW name AS SELECT ...",
        params: &[],
        category: DocCategory::Keyword,
    },
    DocEntry {
        name: "PROCEDURE",
        description: "Creates a stored procedure",
        syntax: "CREATE PROCEDURE name @param TYPE AS BEGIN ... END",
        params: &[],
        category: DocCategory::Keyword,
    },
    DocEntry {
        name: "IF",
        description: "Conditional execution",
        syntax: "IF condition BEGIN ... END ELSE BEGIN ... END",
        params: &[],
        category: DocCategory::Keyword,
    },
    DocEntry {
        name: "ELSE",
        description: "Alternative branch for IF",
        syntax: "IF ... ELSE ...",
        params: &[],
        category: DocCategory::Keyword,
    },
    DocEntry {
        name: "BEGIN",
        description: "Starts a statement block",
        syntax: "BEGIN ... END",
        params: &[],
        category: DocCategory::Keyword,
    },
    DocEntry {
        name: "END",
        description: "Ends a statement block",
        syntax: "BEGIN ... END",
        params: &[],
        category: DocCategory::Keyword,
    },
    DocEntry {
        name: "WHILE",
        description: "Loop construct",
        syntax: "WHILE condition BEGIN ... END",
        params: &[],
        category: DocCategory::Keyword,
    },
    DocEntry {
        name: "RETURN",
        description: "Exits a procedure or batch",
        syntax: "RETURN [value]",
        params: &[],
        category: DocCategory::Keyword,
    },
    DocEntry {
        name: "DECLARE",
        description: "Declares a local variable",
        syntax: "DECLARE @var TYPE [, @var2 TYPE]",
        params: &[],
        category: DocCategory::Keyword,
    },
    DocEntry {
        name: "SET",
        description: "Assigns a value to a variable",
        syntax: "SET @var = expression",
        params: &[],
        category: DocCategory::Keyword,
    },
    DocEntry {
        name: "JOIN",
        description: "Combines rows from two tables",
        syntax: "[INNER|LEFT|RIGHT|FULL] JOIN table ON condition",
        params: &[],
        category: DocCategory::Keyword,
    },
    DocEntry {
        name: "INNER",
        description: "Specifies an inner join",
        syntax: "INNER JOIN table ON condition",
        params: &[],
        category: DocCategory::Keyword,
    },
    DocEntry {
        name: "LEFT",
        description: "Specifies a left outer join",
        syntax: "LEFT JOIN table ON condition",
        params: &[],
        category: DocCategory::Keyword,
    },
    DocEntry {
        name: "RIGHT",
        description: "Specifies a right outer join",
        syntax: "RIGHT JOIN table ON condition",
        params: &[],
        category: DocCategory::Keyword,
    },
    DocEntry {
        name: "ON",
        description: "Specifies join condition",
        syntax: "... JOIN table ON condition",
        params: &[],
        category: DocCategory::Keyword,
    },
    DocEntry {
        name: "AND",
        description: "Logical AND in conditions",
        syntax: "condition1 AND condition2",
        params: &[],
        category: DocCategory::Keyword,
    },
    DocEntry {
        name: "OR",
        description: "Logical OR in conditions",
        syntax: "condition1 OR condition2",
        params: &[],
        category: DocCategory::Keyword,
    },
    DocEntry {
        name: "NOT",
        description: "Logical NOT",
        syntax: "NOT condition",
        params: &[],
        category: DocCategory::Keyword,
    },
    DocEntry {
        name: "IN",
        description: "Checks if value is in a set",
        syntax: "column IN (val1, val2, ...)",
        params: &[],
        category: DocCategory::Keyword,
    },
    DocEntry {
        name: "EXISTS",
        description: "Checks if subquery returns rows",
        syntax: "EXISTS (SELECT ...)",
        params: &[],
        category: DocCategory::Keyword,
    },
    DocEntry {
        name: "BETWEEN",
        description: "Range check",
        syntax: "column BETWEEN val1 AND val2",
        params: &[],
        category: DocCategory::Keyword,
    },
    DocEntry {
        name: "LIKE",
        description: "Pattern matching",
        syntax: "column LIKE 'pattern%'",
        params: &[],
        category: DocCategory::Keyword,
    },
    DocEntry {
        name: "IS",
        description: "NULL check",
        syntax: "column IS [NOT] NULL",
        params: &[],
        category: DocCategory::Keyword,
    },
    DocEntry {
        name: "NULL",
        description: "Represents missing or unknown data",
        syntax: "column IS NULL | column = NULL",
        params: &[],
        category: DocCategory::Keyword,
    },
    DocEntry {
        name: "ORDER",
        description: "Sorts query results",
        syntax: "ORDER BY col1 [ASC|DESC], col2",
        params: &[],
        category: DocCategory::Keyword,
    },
    DocEntry {
        name: "BY",
        description: "Used with ORDER, GROUP",
        syntax: "ORDER BY | GROUP BY",
        params: &[],
        category: DocCategory::Keyword,
    },
    DocEntry {
        name: "GROUP",
        description: "Groups rows for aggregation",
        syntax: "GROUP BY col1, col2",
        params: &[],
        category: DocCategory::Keyword,
    },
    DocEntry {
        name: "HAVING",
        description: "Filters grouped results",
        syntax: "GROUP BY ... HAVING condition",
        params: &[],
        category: DocCategory::Keyword,
    },
    DocEntry {
        name: "UNION",
        description: "Combines result sets",
        syntax: "SELECT ... UNION [ALL] SELECT ...",
        params: &[],
        category: DocCategory::Keyword,
    },
    DocEntry {
        name: "DISTINCT",
        description: "Removes duplicate rows",
        syntax: "SELECT DISTINCT col1, col2 ...",
        params: &[],
        category: DocCategory::Keyword,
    },
    DocEntry {
        name: "CASE",
        description: "Conditional expression",
        syntax: "CASE WHEN cond THEN val ELSE val END",
        params: &[],
        category: DocCategory::Keyword,
    },
    DocEntry {
        name: "WHEN",
        description: "Condition branch in CASE",
        syntax: "CASE WHEN condition THEN result",
        params: &[],
        category: DocCategory::Keyword,
    },
    DocEntry {
        name: "THEN",
        description: "Result in CASE WHEN",
        syntax: "WHEN condition THEN result",
        params: &[],
        category: DocCategory::Keyword,
    },
    DocEntry {
        name: "AS",
        description: "Creates an alias",
        syntax: "column AS alias | table AS alias",
        params: &[],
        category: DocCategory::Keyword,
    },
    DocEntry {
        name: "PRIMARY",
        description: "Primary key constraint",
        syntax: "PRIMARY KEY (col1, col2)",
        params: &[],
        category: DocCategory::Keyword,
    },
    DocEntry {
        name: "FOREIGN",
        description: "Foreign key constraint",
        syntax: "FOREIGN KEY (col) REFERENCES table(col)",
        params: &[],
        category: DocCategory::Keyword,
    },
    DocEntry {
        name: "KEY",
        description: "Constraint keyword",
        syntax: "PRIMARY KEY | FOREIGN KEY",
        params: &[],
        category: DocCategory::Keyword,
    },
    DocEntry {
        name: "REFERENCES",
        description: "Referenced table/column",
        syntax: "FOREIGN KEY (col) REFERENCES table(col)",
        params: &[],
        category: DocCategory::Keyword,
    },
    DocEntry {
        name: "UNIQUE",
        description: "Unique constraint",
        syntax: "UNIQUE (col1, col2)",
        params: &[],
        category: DocCategory::Keyword,
    },
    DocEntry {
        name: "CHECK",
        description: "Check constraint",
        syntax: "CHECK (condition)",
        params: &[],
        category: DocCategory::Keyword,
    },
    DocEntry {
        name: "DEFAULT",
        description: "Default value for column",
        syntax: "col TYPE DEFAULT value",
        params: &[],
        category: DocCategory::Keyword,
    },
    DocEntry {
        name: "IDENTITY",
        description: "Auto-increment column",
        syntax: "col INT IDENTITY(1,1)",
        params: &[],
        category: DocCategory::Keyword,
    },
    DocEntry {
        name: "CONSTRAINT",
        description: "Named constraint",
        syntax: "CONSTRAINT name PRIMARY KEY (col)",
        params: &[],
        category: DocCategory::Keyword,
    },
    DocEntry {
        name: "TRY",
        description: "Starts error handling block",
        syntax: "BEGIN TRY ... END TRY BEGIN CATCH ... END CATCH",
        params: &[],
        category: DocCategory::Keyword,
    },
    DocEntry {
        name: "CATCH",
        description: "Catches errors in TRY block",
        syntax: "BEGIN TRY ... BEGIN CATCH ... END CATCH",
        params: &[],
        category: DocCategory::Keyword,
    },
    DocEntry {
        name: "THROW",
        description: "Raises an error",
        syntax: "THROW error_number, 'message', state",
        params: &[],
        category: DocCategory::Keyword,
    },
    DocEntry {
        name: "COMMIT",
        description: "Commits a transaction",
        syntax: "COMMIT [TRAN[SACTION] [name]]",
        params: &[],
        category: DocCategory::Keyword,
    },
    DocEntry {
        name: "ROLLBACK",
        description: "Rolls back a transaction",
        syntax: "ROLLBACK [TRAN[SACTION] [name]]",
        params: &[],
        category: DocCategory::Keyword,
    },
    DocEntry {
        name: "TRANSACTION",
        description: "Transaction management",
        syntax: "BEGIN TRANSACTION | COMMIT | ROLLBACK",
        params: &[],
        category: DocCategory::Keyword,
    },
    DocEntry {
        name: "GRANT",
        description: "Grants permissions",
        syntax: "GRANT SELECT ON table TO user",
        params: &[],
        category: DocCategory::Keyword,
    },
    DocEntry {
        name: "REVOKE",
        description: "Removes permissions",
        syntax: "REVOKE SELECT ON table FROM user",
        params: &[],
        category: DocCategory::Keyword,
    },
    DocEntry {
        name: "EXEC",
        description: "Executes a stored procedure",
        syntax: "EXEC [@ret =] procedure @param = value",
        params: &[],
        category: DocCategory::Keyword,
    },
    DocEntry {
        name: "EXECUTE",
        description: "Executes a stored procedure",
        syntax: "EXECUTE [@ret =] procedure @param = value",
        params: &[],
        category: DocCategory::Keyword,
    },
    DocEntry {
        name: "PRINT",
        description: "Outputs a message",
        syntax: "PRINT 'message'",
        params: &[],
        category: DocCategory::Keyword,
    },
    DocEntry {
        name: "GO",
        description: "Batch separator (ASE/Sybase)",
        syntax: "GO [count]",
        params: &[],
        category: DocCategory::Keyword,
    },
    DocEntry {
        name: "TOP",
        description: "Limits rows returned",
        syntax: "SELECT TOP n * FROM table",
        params: &[],
        category: DocCategory::Keyword,
    },
];
