//! JavaScript-friendly token representations

use tsql_lexer::Token as LexerToken;
use tsql_token::{Position, Span, TokenKind};

/// JavaScript-friendly token
#[cfg(feature = "wasm")]
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct JsToken {
    /// Token kind
    pub kind: JsTokenKind,
    /// Token text
    pub text: String,
    /// Position information
    pub span: JsSpan,
}

#[cfg(feature = "wasm")]
impl From<LexerToken<'_>> for JsToken {
    fn from(token: LexerToken<'_>) -> Self {
        Self {
            kind: JsTokenKind::from(token.kind),
            text: token.text.to_string(),
            span: JsSpan::from(token.span),
        }
    }
}

/// JavaScript-friendly token kind
///
/// This enum represents all possible token types in T-SQL.
/// The variants are self-explanatory and correspond to SQL keywords,
/// operators, and literals.
#[cfg(feature = "wasm")]
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "snake_case")]
#[allow(missing_docs)]
pub enum JsTokenKind {
    // Keywords
    Select,
    Insert,
    Update,
    Delete,
    Merge,
    From,
    Where,
    Join,
    Inner,
    Outer,
    Left,
    Right,
    Full,
    Cross,
    On,
    And,
    Or,
    Not,
    In,
    Exists,
    Between,
    Like,
    Is,
    Null,
    Order,
    By,
    Asc,
    Desc,
    Group,
    Having,
    Union,
    Intersect,
    Except,
    Distinct,
    All,
    Top,
    Limit,
    Offset,
    First,
    Next,
    Rows,
    Only,
    Create,
    Alter,
    Drop,
    Truncate,
    Table,
    Index,
    View,
    Procedure,
    Proc,
    Function,
    Trigger,
    Database,
    Schema,
    Constraint,
    Primary,
    Foreign,
    Key,
    References,
    Unique,
    Check,
    Default,
    Identity,
    Autoincrement,
    If,
    Else,
    Begin,
    End,
    While,
    Return,
    Break,
    Continue,
    Case,
    When,
    Then,
    Else_,
    End_,
    Try,
    Catch,
    Throw,
    Raiserror,
    Commit,
    Rollback,
    Transaction,
    Tran,
    Save,
    Savepoint,
    Int,
    Integer,
    Smallint,
    Tinyint,
    Bigint,
    Real,
    Double,
    Decimal,
    Numeric,
    Money,
    Smallmoney,
    Char,
    Varchar,
    Text,
    Nchar,
    Nvarchar,
    Ntext,
    Unichar,
    Univarchar,
    Unitext,
    Binary,
    Varbinary,
    Image,
    Date,
    Time,
    Datetime,
    Smalldatetime,
    Timestamp,
    Bigdatetime,
    Bit,
    Uniqueidentifier,
    As,
    Set,
    Declare,
    Exec,
    Execute,
    Into,
    Values,
    Output,
    Cursor,
    Open,
    Close,
    Deallocate,
    Escape,
    Grant,
    Revoke,
    Deny,
    Print,
    Waitfor,
    Goto,
    Label,
    Go,
    // Literals
    Ident,
    QuotedIdent,
    Number,
    FloatLiteral,
    String,
    NString,
    UnicodeString,
    HexString,
    // Operators
    Eq,
    Ne,
    NeAlt,
    Lt,
    Gt,
    Le,
    Ge,
    NotLt,
    NotGt,
    Plus,
    Minus,
    Star,
    Slash,
    Percent,
    Ampersand,
    Pipe,
    Caret,
    Tilde,
    Assign,
    PlusAssign,
    MinusAssign,
    StarAssign,
    SlashAssign,
    Concat,
    // Punctuation
    LParen,
    RParen,
    LBracket,
    RBracket,
    LBrace,
    RBrace,
    Comma,
    Semicolon,
    Colon,
    Dot,
    DotDot,
    // Variable prefixes
    LocalVar,
    GlobalVar,
    TempTable,
    GlobalTempTable,
    // Special
    Whitespace,
    Newline,
    LineComment,
    BlockComment,
    Eof,
    Unknown,
    Using,
}

#[cfg(feature = "wasm")]
impl From<TokenKind> for JsTokenKind {
    fn from(kind: TokenKind) -> Self {
        match kind {
            TokenKind::Select => Self::Select,
            TokenKind::Insert => Self::Insert,
            TokenKind::Update => Self::Update,
            TokenKind::Delete => Self::Delete,
            TokenKind::Merge => Self::Merge,
            TokenKind::From => Self::From,
            TokenKind::Where => Self::Where,
            TokenKind::Join => Self::Join,
            TokenKind::Inner => Self::Inner,
            TokenKind::Outer => Self::Outer,
            TokenKind::Left => Self::Left,
            TokenKind::Right => Self::Right,
            TokenKind::Full => Self::Full,
            TokenKind::Cross => Self::Cross,
            TokenKind::On => Self::On,
            TokenKind::And => Self::And,
            TokenKind::Or => Self::Or,
            TokenKind::Not => Self::Not,
            TokenKind::In => Self::In,
            TokenKind::Exists => Self::Exists,
            TokenKind::Between => Self::Between,
            TokenKind::Like => Self::Like,
            TokenKind::Is => Self::Is,
            TokenKind::Null => Self::Null,
            TokenKind::Order => Self::Order,
            TokenKind::By => Self::By,
            TokenKind::Asc => Self::Asc,
            TokenKind::Desc => Self::Desc,
            TokenKind::Group => Self::Group,
            TokenKind::Having => Self::Having,
            TokenKind::Union => Self::Union,
            TokenKind::Intersect => Self::Intersect,
            TokenKind::Except => Self::Except,
            TokenKind::Distinct => Self::Distinct,
            TokenKind::All => Self::All,
            TokenKind::Top => Self::Top,
            TokenKind::Limit => Self::Limit,
            TokenKind::Offset => Self::Offset,
            TokenKind::First => Self::First,
            TokenKind::Next => Self::Next,
            TokenKind::Rows => Self::Rows,
            TokenKind::Only => Self::Only,
            TokenKind::Create => Self::Create,
            TokenKind::Alter => Self::Alter,
            TokenKind::Drop => Self::Drop,
            TokenKind::Truncate => Self::Truncate,
            TokenKind::Table => Self::Table,
            TokenKind::Index => Self::Index,
            TokenKind::View => Self::View,
            TokenKind::Procedure => Self::Procedure,
            TokenKind::Proc => Self::Proc,
            TokenKind::Function => Self::Function,
            TokenKind::Trigger => Self::Trigger,
            TokenKind::Database => Self::Database,
            TokenKind::Schema => Self::Schema,
            TokenKind::Constraint => Self::Constraint,
            TokenKind::Primary => Self::Primary,
            TokenKind::Foreign => Self::Foreign,
            TokenKind::Key => Self::Key,
            TokenKind::References => Self::References,
            TokenKind::Unique => Self::Unique,
            TokenKind::Check => Self::Check,
            TokenKind::Default => Self::Default,
            TokenKind::Identity => Self::Identity,
            TokenKind::Autoincrement => Self::Autoincrement,
            TokenKind::If => Self::If,
            TokenKind::Else => Self::Else,
            TokenKind::Begin => Self::Begin,
            TokenKind::End => Self::End,
            TokenKind::While => Self::While,
            TokenKind::Return => Self::Return,
            TokenKind::Break => Self::Break,
            TokenKind::Continue => Self::Continue,
            TokenKind::Case => Self::Case,
            TokenKind::When => Self::When,
            TokenKind::Then => Self::Then,
            TokenKind::Else_ => Self::Else_,
            TokenKind::End_ => Self::End_,
            TokenKind::Try => Self::Try,
            TokenKind::Catch => Self::Catch,
            TokenKind::Throw => Self::Throw,
            TokenKind::Raiserror => Self::Raiserror,
            TokenKind::Commit => Self::Commit,
            TokenKind::Rollback => Self::Rollback,
            TokenKind::Transaction => Self::Transaction,
            TokenKind::Tran => Self::Tran,
            TokenKind::Save => Self::Save,
            TokenKind::Savepoint => Self::Savepoint,
            TokenKind::Int => Self::Int,
            TokenKind::Integer => Self::Integer,
            TokenKind::Smallint => Self::Smallint,
            TokenKind::Tinyint => Self::Tinyint,
            TokenKind::Bigint => Self::Bigint,
            TokenKind::Real => Self::Real,
            TokenKind::Double => Self::Double,
            TokenKind::Decimal => Self::Decimal,
            TokenKind::Numeric => Self::Numeric,
            TokenKind::Money => Self::Money,
            TokenKind::Smallmoney => Self::Smallmoney,
            TokenKind::Char => Self::Char,
            TokenKind::Varchar => Self::Varchar,
            TokenKind::Text => Self::Text,
            TokenKind::Nchar => Self::Nchar,
            TokenKind::Nvarchar => Self::Nvarchar,
            TokenKind::Ntext => Self::Ntext,
            TokenKind::Unichar => Self::Unichar,
            TokenKind::Univarchar => Self::Univarchar,
            TokenKind::Unitext => Self::Unitext,
            TokenKind::Binary => Self::Binary,
            TokenKind::Varbinary => Self::Varbinary,
            TokenKind::Image => Self::Image,
            TokenKind::Date => Self::Date,
            TokenKind::Time => Self::Time,
            TokenKind::Datetime => Self::Datetime,
            TokenKind::Smalldatetime => Self::Smalldatetime,
            TokenKind::Timestamp => Self::Timestamp,
            TokenKind::Bigdatetime => Self::Bigdatetime,
            TokenKind::Bit => Self::Bit,
            TokenKind::Uniqueidentifier => Self::Uniqueidentifier,
            TokenKind::As => Self::As,
            TokenKind::Set => Self::Set,
            TokenKind::Declare => Self::Declare,
            TokenKind::Exec => Self::Exec,
            TokenKind::Execute => Self::Execute,
            TokenKind::Into => Self::Into,
            TokenKind::Values => Self::Values,
            TokenKind::Output => Self::Output,
            TokenKind::Cursor => Self::Cursor,
            TokenKind::Open => Self::Open,
            TokenKind::Close => Self::Close,
            TokenKind::Deallocate => Self::Deallocate,
            TokenKind::Escape => Self::Escape,
            TokenKind::Grant => Self::Grant,
            TokenKind::Revoke => Self::Revoke,
            TokenKind::Deny => Self::Deny,
            TokenKind::Print => Self::Print,
            TokenKind::Waitfor => Self::Waitfor,
            TokenKind::Goto => Self::Goto,
            TokenKind::Label => Self::Label,
            TokenKind::Go => Self::Go,
            TokenKind::Ident => Self::Ident,
            TokenKind::QuotedIdent => Self::QuotedIdent,
            TokenKind::Number => Self::Number,
            TokenKind::FloatLiteral => Self::FloatLiteral,
            TokenKind::String => Self::String,
            TokenKind::NString => Self::NString,
            TokenKind::UnicodeString => Self::UnicodeString,
            TokenKind::HexString => Self::HexString,
            TokenKind::Eq => Self::Eq,
            TokenKind::Ne => Self::Ne,
            TokenKind::NeAlt => Self::NeAlt,
            TokenKind::Lt => Self::Lt,
            TokenKind::Gt => Self::Gt,
            TokenKind::Le => Self::Le,
            TokenKind::Ge => Self::Ge,
            TokenKind::NotLt => Self::NotLt,
            TokenKind::NotGt => Self::NotGt,
            TokenKind::Plus => Self::Plus,
            TokenKind::Minus => Self::Minus,
            TokenKind::Star => Self::Star,
            TokenKind::Slash => Self::Slash,
            TokenKind::Percent => Self::Percent,
            TokenKind::Ampersand => Self::Ampersand,
            TokenKind::Pipe => Self::Pipe,
            TokenKind::Caret => Self::Caret,
            TokenKind::Tilde => Self::Tilde,
            TokenKind::Assign => Self::Assign,
            TokenKind::PlusAssign => Self::PlusAssign,
            TokenKind::MinusAssign => Self::MinusAssign,
            TokenKind::StarAssign => Self::StarAssign,
            TokenKind::SlashAssign => Self::SlashAssign,
            TokenKind::Concat => Self::Concat,
            TokenKind::LParen => Self::LParen,
            TokenKind::RParen => Self::RParen,
            TokenKind::LBracket => Self::LBracket,
            TokenKind::RBracket => Self::RBracket,
            TokenKind::LBrace => Self::LBrace,
            TokenKind::RBrace => Self::RBrace,
            TokenKind::Comma => Self::Comma,
            TokenKind::Semicolon => Self::Semicolon,
            TokenKind::Colon => Self::Colon,
            TokenKind::Dot => Self::Dot,
            TokenKind::DotDot => Self::DotDot,
            TokenKind::LocalVar => Self::LocalVar,
            TokenKind::GlobalVar => Self::GlobalVar,
            TokenKind::TempTable => Self::TempTable,
            TokenKind::GlobalTempTable => Self::GlobalTempTable,
            TokenKind::Whitespace => Self::Whitespace,
            TokenKind::Newline => Self::Newline,
            TokenKind::LineComment => Self::LineComment,
            TokenKind::BlockComment => Self::BlockComment,
            TokenKind::Eof => Self::Eof,
            TokenKind::Unknown => Self::Unknown,
            TokenKind::Using => Self::Using,
        }
    }
}

/// JavaScript-friendly position
#[cfg(feature = "wasm")]
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct JsPosition {
    /// Line number (1-indexed)
    pub line: u32,
    /// Column number (1-indexed)
    pub column: u32,
    /// Byte offset (0-indexed)
    pub offset: u32,
}

#[cfg(feature = "wasm")]
impl From<Position> for JsPosition {
    fn from(pos: Position) -> Self {
        Self {
            line: pos.line,
            column: pos.column,
            offset: pos.offset,
        }
    }
}

/// JavaScript-friendly span
#[cfg(feature = "wasm")]
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct JsSpan {
    /// Start byte offset
    pub start: u32,
    /// End byte offset (exclusive)
    pub end: u32,
}

#[cfg(feature = "wasm")]
impl From<Span> for JsSpan {
    fn from(span: Span) -> Self {
        Self {
            start: span.start,
            end: span.end,
        }
    }
}
