name: "Rust CodeCov"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        components: llvm-tools-preview
    - name: Install llvm-tools
      run: rustup component add llvm-tools-preview
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
      env:
        CARGO_INCREMENTAL: '0'
        RUSTFLAGS: '-C instrument-coverage'
        RUSTDOCFLAGS: '-C instrument-coverage'
        LLVM_PROFILE_FILE: 'coverage-%p-%m.profraw'
    - name: Install grcov
      run: cargo install grcov
    - name: Generate coverage report
      run: |
        grcov . --binary-path ./target/debug/ \
          -s . \
          -t lcov \
          --branch \
          --ignore-not-existing \
          --ignore '../*' \
          --ignore "/*" \
          -o lcov.info
    - name: Codecov
      uses: codecov/codecov-action@v5
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        verbose: true
        fail_ci_if_error: false
        files: ./lcov.info
